# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'CCSDKiOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CCSDKiOS
  
    # UI
    pod 'TPKeyboardAvoiding', '~> 1.3'
    pod 'UITextView+Placeholder'
    pod 'KSToastView', '~> 0.5'
    pod 'BRYXBanner', '~> 0.8'
    pod 'SVProgressHUD'
    pod 'ActionSheetPicker-3.0', '~> 2.2'
    
    # Networking
    pod 'Kingfisher', '~> 4.8'
    pod 'Alamofire', '~> 4.5'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'Gloss', '~> 2.0'
    
    # Location
    pod 'INTULocationManager'
    
    # Logs and Reporting
    pod 'Fabric'
    pod 'Crashlytics'
    
    #Firebase
    #pod 'Firebase/Core'
    #pod 'Firebase/Messaging'

end
